workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.najdalmotatorh.carby
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          xcode-project use-profiles
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
